// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace specflow_test
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Pesquisar wiki", Description="Como usuario \r\nQuero pesquisar por um termo\r\nde modo que obtenha o resultado espe" +
        "rado", SourceFile="SpecFlowFeature1.feature", SourceLine=4)]
    public partial class PesquisarWikiFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Pesquisar wiki", "Como usuario \r\nQuero pesquisar por um termo\r\nde modo que obtenha o resultado espe" +
                    "rado", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void PesquisarWiki(string url, string pesquisa, string paginasucesso, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("pesquisar wiki", exampleTags);
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
testRunner.Given(string.Format("que acesse a pagina {0}", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 12
testRunner.And(string.Format("faça a pesquisa {0}", pesquisa), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
testRunner.When("acionar o botão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 14
testRunner.Then(string.Format("resultado é exibido {0}", paginasucesso), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 15
testRunner.And("fechar pagina", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("pesquisar wiki, \"https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:P%C3%A1gina_princip" +
            "al\"", SourceLine=18)]
        public virtual void PesquisarWiki_HttpsPt_Wikipedia_OrgWikiWikipC3A9DiaPC3A1Gina_Principal()
        {
            this.PesquisarWiki("\"https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:P%C3%A1gina_principal\"", "\"teste\"", "\"Teste\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
